#!/usr/bin/env bash
# CoreWAF Starter Kit — installer.
#
# v0 (feature/tunnel-v0): the kit is token-driven. The customer pastes
# (or env-supplies) a single self-locating provisioning_token; the rest
# — api gateway URL, observability endpoints, zero-trust API key, WG
# tunnel config — arrives on first boot via the redemption response.
#
# Plain bash + plain stdout. No TUI dependency, no spinners eating
# subprocess stderr.

set -euo pipefail

# ── locate kit root ───────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_INI="${REPO_ROOT}/config.ini"

DO_UP=1
for arg in "$@"; do
    case "$arg" in
        --no-up) DO_UP=0 ;;
        -h|--help)
            cat <<EOF
Usage: ./scripts/install.sh [--no-up]

Writes config.ini (one prompt: the provisioning token, unless TOKEN
env is already set), then runs 'docker compose up -d' through three
stages (init, tunnel, services). --no-up writes config and stops.

Env vars:
  TOKEN              Provisioning token (alias: COREWAF_TOKEN). Skips
                     the prompt; required when stdin isn't a TTY.
  INSTANCE_COMMENT   Free-form label (alias: COREWAF_INSTANCE_COMMENT).
EOF
            exit 0
            ;;
    esac
done

step() { printf '\n── %s ──\n' "$*"; }
note() { printf '%s\n' "$*"; }
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# ── preflight ─────────────────────────────────────────────────────────
step "CoreWAF Starter Kit — installer"

command -v docker >/dev/null 2>&1 || fail "docker is required but not on PATH"
docker compose version >/dev/null 2>&1 || fail "'docker compose' plugin is required (compose v2)"

# ── token + comment ──────────────────────────────────────────────────
PROVISIONING_TOKEN="${TOKEN:-${COREWAF_TOKEN:-}}"
INSTANCE_COMMENT="${INSTANCE_COMMENT:-${COREWAF_INSTANCE_COMMENT:-}}"

if [ -z "${PROVISIONING_TOKEN}" ] && [ ! -t 0 ]; then
    cat <<'EOF' >&2
ERROR: TOKEN is empty.

  When running via curl, use process substitution so TOKEN reaches bash:

    TOKEN=v1.eyJ... bash <(curl -fsSL <bootstrap-url>)

  (NOT `TOKEN=… curl … | bash` — env-prefix on a pipeline applies
   only to curl, not to bash on the right side of the pipe.)

  Or run the installer locally and answer the prompt:

    bash scripts/install.sh
EOF
    exit 1
fi

while [ -z "${PROVISIONING_TOKEN}" ]; do
    printf 'Provisioning token (v1.<payload>.<sig>): '
    IFS= read -r PROVISIONING_TOKEN
    [ -z "${PROVISIONING_TOKEN}" ] && note "Token is required."
done

# Validate envelope shape regardless of whether it came from prompt or env.
case "${PROVISIONING_TOKEN}" in
    v1.*.*) ;;
    *) fail "TOKEN doesn't look like a v1 envelope (v1.<payload>.<sig>)" ;;
esac

# ── write config.ini + compose-time .env ──────────────────────────────
step "Writing ${CONFIG_INI}"

if [ -f "${CONFIG_INI}" ]; then
    note "Overwriting existing config.ini."
fi

cat > "${CONFIG_INI}" <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run the installer to regenerate.

provisioning_token=${PROVISIONING_TOKEN}
instance_comment=${INSTANCE_COMMENT}

# v0 transitional placeholders — the instance-init image still
# validates these as non-empty. Real values arrive in the redemption
# response and the tunnel-client writes them into runtime/.env after
# init completes. Drop once instance-init is updated to v0.
org_scope_id=pending-redemption
observability_base_url=pending.redemption.local
api_gateway_url=http://pending.redemption.local
EOF

# Compose-time .env at the kit root. Holds substitution values
# (NOT runtime env). Today: the host's docker group GID, so the
# bridge container can read /var/run/docker.sock for restart /
# get-logs action handlers.
DOCKER_GID="$(getent group docker 2>/dev/null | cut -d: -f3 || true)"
if [ -z "${DOCKER_GID}" ]; then
    note "(docker group not found on host — falling back to GID 999; restart actions may fail)"
    DOCKER_GID=999
fi

cat > "${REPO_ROOT}/.env" <<EOF
# Compose-time variable substitutions. Not consumed by running
# containers (those read runtime/.env, rendered by init + tunnel).
DOCKER_GID=${DOCKER_GID}
EOF

note "Wrote config.ini and .env (DOCKER_GID=${DOCKER_GID})."

# ── bring up the stack ────────────────────────────────────────────────
if [ "${DO_UP}" = "0" ]; then
    note "Skipping bring-up (--no-up). When ready: cd '${REPO_ROOT}' && docker compose up -d"
    exit 0
fi

cd "${REPO_ROOT}"

# Compose evaluates env_file at container CREATE time, not start time,
# so we run init separately first (renders runtime/.env from config.ini
# + discovery). Tunnel then redeems the token and OVERWRITES runtime/.env
# with the real values before caddy-bridge is created.
mkdir -p runtime
[ -f runtime/.env ] || : > runtime/.env

step "Stage 1: init (privileged — discovery + template render)"
docker compose run --rm init

step "Stage 2: tunnel (redeem token + bring up wg100)"
docker compose up -d --no-deps tunnel

# We must NOT let stage 3 (`compose up caddy …`) re-trigger init —
# that would re-render runtime/.env from the placeholder config.ini
# values and clobber what the tunnel just wrote. --no-deps in stage 3
# avoids that, but it also bypasses caddy-bridge's dependency on
# tunnel: service_healthy, so we wait here ourselves.
note "Waiting for tunnel to become healthy ..."
_deadline=$(( $(date +%s) + 60 ))
_status=
while [ "$(date +%s)" -lt "${_deadline}" ]; do
    _status="$(docker compose ps --format '{{.Health}}' tunnel 2>/dev/null | head -1)"
    [ "${_status}" = "healthy" ] && break
    sleep 2
done
if [ "${_status}" != "healthy" ]; then
    echo "ERROR: tunnel did not become healthy within 60s" >&2
    docker compose logs --tail=30 tunnel >&2
    exit 1
fi
note "Tunnel healthy."

step "Stage 3: caddy + bridge + alloy + valkey"
docker compose up -d --no-deps caddy caddy-bridge alloy valkey

cat <<EOF

Stack is up. Tail logs with:
  docker compose logs -f tunnel        # WG bring-up + redemption
  docker compose logs -f caddy-bridge  # bridge registration

Caddy waits for the CoreWAF backend to provision it before serving traffic;
telemetry starts flowing immediately via Alloy.
EOF
