#!/usr/bin/env bash
# CoreWAF Starter Kit — interactive installer.
#
# Walks the customer through the two required config.ini values
# (org_scope_id, observability_base_url) plus the optional instance
# comment. Writes config.ini in the repo root and (unless --no-up)
# launches the stack with `docker compose up -d`.
#
# Uses `gum` for the TUI when available; falls back to plain `read` so
# the script works on any POSIX host.
#
# Eventually replaced by an API-key-driven curl bootstrap that auto-fills
# config.ini via the discovery service over the Zero Trust tunnel — see
# docs/requirements.md §2.

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve repo root regardless of where the script is invoked from.
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_INI="${REPO_ROOT}/config.ini"
EXAMPLE_INI="${REPO_ROOT}/config.ini.example"

DO_UP=1
for arg in "$@"; do
    case "$arg" in
        --no-up) DO_UP=0 ;;
        -h|--help)
            cat <<EOF
Usage: ./scripts/install.sh [--no-up]

Interactive installer. Writes config.ini in the repo root from your
answers, then runs 'docker compose up -d' (skip with --no-up).
EOF
            exit 0
            ;;
    esac
done

# ---------------------------------------------------------------------------
# UI helpers — gum if present, plain read otherwise.
# ---------------------------------------------------------------------------
HAS_GUM=0
if command -v gum >/dev/null 2>&1; then
    HAS_GUM=1
fi

ui_header() {
    if [ "${HAS_GUM}" = "1" ]; then
        gum style --bold --foreground 212 --margin "1 0" "$1"
    else
        printf '\n=== %s ===\n' "$1"
    fi
}

ui_note() {
    if [ "${HAS_GUM}" = "1" ]; then
        gum style --foreground 245 "$1"
    else
        printf '%s\n' "$1"
    fi
}

ui_input() {
    # $1: prompt   $2: placeholder (optional)
    local prompt="$1"
    local placeholder="${2:-}"
    if [ "${HAS_GUM}" = "1" ]; then
        gum input --prompt "${prompt}> " --placeholder "${placeholder}"
    else
        local answer
        printf '%s ' "${prompt}>" >&2
        IFS= read -r answer
        printf '%s' "${answer}"
    fi
}

ui_confirm() {
    # $1: question. exits 0 (yes) or 1 (no).
    if [ "${HAS_GUM}" = "1" ]; then
        gum confirm "$1"
    else
        local answer
        printf '%s [y/N] ' "$1" >&2
        IFS= read -r answer
        case "${answer}" in
            y|Y|yes|YES) return 0 ;;
            *) return 1 ;;
        esac
    fi
}

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
ui_header "CoreWAF Starter Kit — Installer"

if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: docker is required but not on PATH" >&2
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    echo "ERROR: 'docker compose' plugin is required (compose v2)" >&2
    exit 1
fi

if [ "${HAS_GUM}" = "0" ]; then
    ui_note "(gum not installed — using plain prompts. Install gum for a nicer experience: https://github.com/charmbracelet/gum)"
fi

if [ -f "${CONFIG_INI}" ]; then
    if ! ui_confirm "config.ini already exists — overwrite?"; then
        echo "Keeping existing config.ini. Re-run with --no-up if you only want the prompts." >&2
        exit 0
    fi
fi

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------
ui_header "Tell us about this instance"

ORG_SCOPE_ID=""
while [ -z "${ORG_SCOPE_ID}" ]; do
    ORG_SCOPE_ID=$(ui_input "Org scope ID" "your-org-name")
    [ -z "${ORG_SCOPE_ID}" ] && ui_note "Org scope ID is required."
done

OBSERVABILITY_BASE_URL=""
while [ -z "${OBSERVABILITY_BASE_URL}" ]; do
    OBSERVABILITY_BASE_URL=$(ui_input "Observability base URL" "https://platform.corewaf.example.com")
    case "${OBSERVABILITY_BASE_URL}" in
        http://*|https://*) ;;
        "") ui_note "Observability base URL is required." ;;
        *)
            ui_note "URL must start with http:// or https://"
            OBSERVABILITY_BASE_URL=""
            ;;
    esac
done

INSTANCE_COMMENT=$(ui_input "Instance comment (optional, free-form)" "rack 4, slot 7")

# ---------------------------------------------------------------------------
# Write config.ini
# ---------------------------------------------------------------------------
ui_header "Writing config.ini"

cat > "${CONFIG_INI}" <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run the installer to regenerate, or edit by hand.

org_scope_id=${ORG_SCOPE_ID}
observability_base_url=${OBSERVABILITY_BASE_URL}
instance_comment=${INSTANCE_COMMENT}
EOF

ui_note "Wrote ${CONFIG_INI}"

# ---------------------------------------------------------------------------
# Bring up the stack
# ---------------------------------------------------------------------------
if [ "${DO_UP}" = "0" ]; then
    ui_note "Skipping 'docker compose up' (--no-up). When ready: cd '${REPO_ROOT}' && docker compose up -d"
    exit 0
fi

ui_header "Bringing up the stack"
ui_note "Stage 1 (discover) is privileged and will take a moment."

cd "${REPO_ROOT}"
docker compose up -d

ui_note "Stack is up. Tail logs with: docker compose logs -f caddy-bridge"
ui_note "Caddy will wait for the CoreWAF backend to provision it before serving traffic; telemetry starts flowing immediately."
