#!/usr/bin/env bash
# CoreWAF Starter Kit — installer.
#
# v2 Phase 1 (foundation tier only): the kit is token-driven. The
# customer pastes (or env-supplies) a single self-locating
# provisioning_token; the kit's tunnel mode decodes the gateway URL
# from the envelope, generates and TPM-binds the kit's mTLS keypair
# via PKCS#11, redeems against the gateway, and persists everything
# the bridge stack will eventually need at the handoff-contract paths
# under /var/lib/tunnel.
#
# Phase 1's compose runs only `init` and `tunnel`. The bridge stack
# (caddy, caddy-bridge, alloy, valkey) is gated behind the `legacy`
# profile and remains v0-shaped until Phase 2 wires the orchestrator
# handoff that launches it from a manifest. The legacy profile is
# offered for diagnostics; it does NOT function end-to-end on a
# Phase 1 kit because runtime/.env is no longer populated.

set -euo pipefail

# ── locate kit root ───────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_INI="${REPO_ROOT}/config.ini"

DO_UP=1
WITH_LEGACY=0
for arg in "$@"; do
    case "$arg" in
        --no-up) DO_UP=0 ;;
        --with-legacy) WITH_LEGACY=1 ;;
        -h|--help)
            cat <<EOF
Usage: ./scripts/install.sh [--no-up] [--with-legacy]

Writes config.ini (one prompt: the provisioning token, unless TOKEN
env is already set), then runs 'docker compose up -d' to bring the
foundation tier (init + tunnel) online.

  --no-up         Write config and stop. When ready:
                  cd '${REPO_ROOT}' && docker compose up -d

  --with-legacy   Also bring up the v0 bridge stack
                  (caddy + caddy-bridge + alloy + valkey) via the
                  'legacy' compose profile. Does NOT function
                  end-to-end on a Phase 1 kit; intended for
                  diagnostics during the v2 transition.

Env vars:
  TOKEN              Provisioning token (alias: COREWAF_TOKEN). Skips
                     the prompt; required when stdin isn't a TTY.
  INSTANCE_COMMENT   Free-form label (alias: COREWAF_INSTANCE_COMMENT).
EOF
            exit 0
            ;;
    esac
done

step() { printf '\n── %s ──\n' "$*"; }
note() { printf '%s\n' "$*"; }
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# ── preflight ─────────────────────────────────────────────────────────
step "CoreWAF Starter Kit — installer (v2 Phase 1)"

command -v docker >/dev/null 2>&1 || fail "docker is required but not on PATH"
docker compose version >/dev/null 2>&1 || fail "'docker compose' plugin is required (compose v2)"

# ── token + comment ──────────────────────────────────────────────────
PROVISIONING_TOKEN="${TOKEN:-${COREWAF_TOKEN:-}}"
INSTANCE_COMMENT="${INSTANCE_COMMENT:-${COREWAF_INSTANCE_COMMENT:-}}"

if [ -z "${PROVISIONING_TOKEN}" ] && [ ! -t 0 ]; then
    cat <<'EOF' >&2
ERROR: TOKEN is empty.

  When running via curl, use process substitution so TOKEN reaches bash:

    TOKEN=v1.eyJ... bash <(curl -fsSL <bootstrap-url>)

  (NOT `TOKEN=… curl … | bash` — env-prefix on a pipeline applies
   only to curl, not to bash on the right side of the pipe.)

  Or run the installer locally and answer the prompt:

    bash scripts/install.sh
EOF
    exit 1
fi

while [ -z "${PROVISIONING_TOKEN}" ]; do
    printf 'Provisioning token (v1.<payload>.<sig>): '
    IFS= read -r PROVISIONING_TOKEN
    [ -z "${PROVISIONING_TOKEN}" ] && note "Token is required."
done

# Sanity-check token shape: three dot-separated segments (JWS).
# network-loader does the full decode + validation; this is just a
# fast-fail for obvious typos at the installer level.
case "${PROVISIONING_TOKEN}" in
    *.*.*) ;;
    *) fail "TOKEN doesn't look like a JWS envelope (<header>.<payload>.<sig>)" ;;
esac

# ── write config.ini ──────────────────────────────────────────────────
step "Writing ${CONFIG_INI}"

if [ -f "${CONFIG_INI}" ]; then
    note "Overwriting existing config.ini."
fi

cat > "${CONFIG_INI}" <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run the installer to regenerate.

provisioning_token=${PROVISIONING_TOKEN}
instance_comment=${INSTANCE_COMMENT}
EOF

note "Wrote config.ini."

# ── bring up the stack ────────────────────────────────────────────────
if [ "${DO_UP}" = "0" ]; then
    note "Skipping bring-up (--no-up). When ready: cd '${REPO_ROOT}' && docker compose up -d"
    exit 0
fi

cd "${REPO_ROOT}"

step "Stage 1: init (host probe → /var/lib/tunnel/discovery.json)"
docker compose run --rm init

step "Stage 2: tunnel (decode token → keys → /redeem → wg100 up → keepalive loop)"
docker compose up -d tunnel

note "Waiting for tunnel to become healthy ..."
_deadline=$(( $(date +%s) + 90 ))
_status=
while [ "$(date +%s)" -lt "${_deadline}" ]; do
    _status="$(docker compose ps --format '{{.Health}}' tunnel 2>/dev/null | head -1)"
    [ "${_status}" = "healthy" ] && break
    sleep 2
done
if [ "${_status}" != "healthy" ]; then
    echo "ERROR: tunnel did not become healthy within 90s" >&2
    docker compose logs --tail=50 tunnel >&2
    exit 1
fi
note "Tunnel healthy. Foundation tier is up."

if [ "${WITH_LEGACY}" = "1" ]; then
    step "Stage 3 (legacy diagnostics): caddy + bridge + alloy + valkey"
    note "WARNING: the legacy bridge stack is not wired against the v2 tunnel."
    note "         These containers will likely fail without runtime/.env."
    docker compose --profile legacy up -d --no-deps caddy caddy-bridge alloy valkey || true
fi

cat <<EOF

Foundation tier is up. Tail logs with:
  docker compose logs -f tunnel        # /redeem flow + WG bring-up + keepalive

The bridge stack (caddy, caddy-bridge, alloy, valkey) does not run
on Phase 1 by default. Phase 2 will add an 'orchestrator' service
that launches them via docker socket from a manifest.
EOF
